### ISSUE TITLE
MVP - Todo List

### ISSUE THREAD

**Issue by pedrorvelloso** [Pixel-Void/server#1]
# TODO list

- [ ] Create server structre
- [ ] Create Database and Database connection
- [ ] Create User Entity
- [ ] Create Void Entity
- [ ] Create Galaxy Entity
- [ ] Create Star Entity
- [ ] Create Users Resolvers
- [ ] Create Voids Resolvers ("galaxies realm" *art galleries*)
- [ ] Create Galaxies Resolvers (art galleries)
- [ ] Create Stars Resolvers (arts)

## Important after MVP is done
- [ ] **Tests**
- [ ] Readme
- [ ] Migrations & Seeds *(?)*
